name: Bruin Test

on: 
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Installs latest
    - uses: bruin-data/bruin-setup-action@main
    - run: bruin validate ./bruin-pipeline/
      name: Validate Pipeline
    - run: bruin format ./bruin-pipeline/
      name: Format Pipeline
    - name: Lineage
      run: |
        bruin lineage bruin-pipeline/assets/example.sql
        bruin lineage bruin-pipeline/assets/pythonsample/country_list.py
      
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    # Installs latest
    - uses: bruin-data/bruin-setup-action@main
    - run: bruin validate ./bruin-pipeline/
      name: Validate Pipeline
    # - run: bruin format ./bruin-pipeline/
    #   name: Format Pipeline
    - name: Lineage
      run: |
        bruin lineage bruin-pipeline/assets/example.sql
        bruin lineage bruin-pipeline/assets/pythonsample/country_list.py
